In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df=pd.read_csv('Titanic-Dataset.csv')

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [25]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [27]:
df['Sex'].mode()[0]

'male'

In [28]:
df.drop(['Name'],axis=1,inplace=True)

In [29]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [30]:
df['Age'].mean()

np.float64(29.69911764705882)

In [31]:
df['Age'].median()

np.float64(28.0)

In [32]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [33]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [36]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.361582,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.019697,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [42]:
df.groupby(['Age','Pclass'])['Survived'].mean()

Age    Pclass
0.42   3         1.0
0.67   2         1.0
0.75   3         1.0
0.83   2         1.0
0.92   1         1.0
                ...
70.00  2         0.0
70.50  3         0.0
71.00  1         0.0
74.00  3         0.0
80.00  1         1.0
Name: Survived, Length: 182, dtype: float64

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    str
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    str
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    str
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

In [44]:
df['Deck']=df['Cabin'].str[0]

In [45]:
df['Deck']

0      NaN
1        C
2      NaN
3        C
4      NaN
      ...
886    NaN
887      B
888    NaN
889      C
890    NaN
Name: Deck, Length: 891, dtype: str

In [46]:
df['Deck']=df['Deck'].fillna('Unknown')

In [54]:
df['Deck'].value_counts()

Deck
Unknown    687
C           59
B           47
D           33
E           32
A           15
F           13
G            4
T            1
Name: count, dtype: int64

In [55]:
df=df.drop(columns=['Cabin'])

In [56]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Deck
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,S,Unknown
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,Unknown
3,4,1,1,female,35.0,1,0,113803,53.1000,S,C
4,5,0,3,male,35.0,0,0,373450,8.0500,S,Unknown
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,13.0000,S,Unknown
887,888,1,1,female,19.0,0,0,112053,30.0000,S,B
888,889,0,3,female,28.0,1,2,W./C. 6607,23.4500,S,Unknown
889,890,1,1,male,26.0,0,0,111369,30.0000,C,C
890,891,0,3,male,32.0,0,0,370376,7.7500,Q,Unknown

In [58]:
ids=df['PassengerId']
df=df.drop(columns=['PassengerId'])

In [62]:
df.groupby('Pclass')['Survived'].mean()*100

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64