In [1]:
!pip install numpy pandas scikit-learn seaborn

Requirement already satisfied: numpy in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.3.5)
Requirement already satisfied: pandas in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.7.2)
Requirement already satisfied: seaborn in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\thego\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt
import seaborn as sns

In [4]:
df=pd.read_csv('accident.csv')

In [5]:
df.head()

   Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
0   56  Female             27.0          No            No         1
1   69  Female             46.0          No           Yes         1
2   46    Male             46.0         Yes           Yes         0
3   32    Male            117.0          No           Yes         0
4   60  Female             40.0         Yes           Yes         0

In [6]:
df.tail()

     Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
195   69  Female            111.0          No           Yes         1
196   30  Female             51.0          No           Yes         1
197   58    Male            110.0          No           Yes         1
198   20    Male            103.0          No           Yes         1
199   56  Female             43.0          No           Yes         1

In [7]:
df.isna().sum()

Age                0
Gender             1
Speed_of_Impact    3
Helmet_Used        0
Seatbelt_Used      0
Survived           0
dtype: int64

In [8]:
missing_values=df.isnull().stack()
missing_location=missing_values[missing_values].index.tolist()
print(missing_location)

[(15, 'Speed_of_Impact'), (19, 'Speed_of_Impact'), (29, 'Speed_of_Impact'), (30, 'Gender')]

In [10]:
df['Speed_of_Impact']=df['Speed_of_Impact'].fillna(df['Speed_of_Impact'].median())

In [11]:
df['Speed_of_Impact'].isna().sum()

np.int64(0)

In [12]:
df['Gender']=df['Gender'].replace({'Female':0,'Male':1})

C:\Users\thego\AppData\Local\Temp\ipykernel_14048\1587202627.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender']=df['Gender'].replace({'Female':0,'Male':1})

In [13]:
df.head()

   Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
0   56     0.0             27.0          No            No         1
1   69     0.0             46.0          No           Yes         1
2   46     1.0             46.0         Yes           Yes         0
3   32     1.0            117.0          No           Yes         0
4   60     0.0             40.0         Yes           Yes         0

In [14]:
mode_gender=df['Gender'].mode()[0]
df['Gender']=df['Gender'].fillna(mode_gender)

In [15]:
df['Gender'].isna().sum()

np.int64(0)

In [16]:
df.info

<bound method DataFrame.info of      Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
0     56     0.0             27.0          No            No         1
1     69     0.0             46.0          No           Yes         1
2     46     1.0             46.0         Yes           Yes         0
3     32     1.0            117.0          No           Yes         0
4     60     0.0             40.0         Yes           Yes         0
..   ...     ...              ...         ...           ...       ...
195   69     0.0            111.0          No           Yes         1
196   30     0.0             51.0          No           Yes         1
197   58     1.0            110.0          No           Yes         1
198   20     1.0            103.0          No           Yes         1
199   56     0.0             43.0          No           Yes         1

[200 rows x 6 columns]>

In [17]:
df.shape

(200, 6)

In [18]:
df['Helmet_Used']=df['Helmet_Used'].replace({'No':0,'Yes':1})

C:\Users\thego\AppData\Local\Temp\ipykernel_14048\2075379354.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Helmet_Used']=df['Helmet_Used'].replace({'No':0,'Yes':1})

In [19]:
df.head()

   Age  Gender  Speed_of_Impact  Helmet_Used Seatbelt_Used  Survived
0   56     0.0             27.0            0            No         1
1   69     0.0             46.0            0           Yes         1
2   46     1.0             46.0            1           Yes         0
3   32     1.0            117.0            0           Yes         0
4   60     0.0             40.0            1           Yes         0

In [20]:
df['Seatbelt_Used']=df['Seatbelt_Used'].replace({'No':0,'Yes':1})

C:\Users\thego\AppData\Local\Temp\ipykernel_14048\2884308357.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Seatbelt_Used']=df['Seatbelt_Used'].replace({'No':0,'Yes':1})

In [21]:
df.head()

   Age  Gender  Speed_of_Impact  Helmet_Used  Seatbelt_Used  Survived
0   56     0.0             27.0            0              0         1
1   69     0.0             46.0            0              1         1
2   46     1.0             46.0            1              1         0
3   32     1.0            117.0            0              1         0
4   60     0.0             40.0            1              1         0

In [22]:
df.info

<bound method DataFrame.info of      Age  Gender  Speed_of_Impact  Helmet_Used  Seatbelt_Used  Survived
0     56     0.0             27.0            0              0         1
1     69     0.0             46.0            0              1         1
2     46     1.0             46.0            1              1         0
3     32     1.0            117.0            0              1         0
4     60     0.0             40.0            1              1         0
..   ...     ...              ...          ...            ...       ...
195   69     0.0            111.0            0              1         1
196   30     0.0             51.0            0              1         1
197   58     1.0            110.0            0              1         1
198   20     1.0            103.0            0              1         1
199   56     0.0             43.0            0              1         1

[200 rows x 6 columns]>

In [23]:
df['Gender']=df['Gender'].apply(int)

In [24]:
from sklearn.preprocessing import StandardScaler

In [27]:
scaler= StandardScaler()
df[['Age','Speed_of_Impact']]=scaler.fit_transform(df[['Age','Speed_of_Impact']])

In [29]:
df.to_csv('processed_data.csv',index=False)

In [30]:
df_new=pd.read_csv('processed_data.csv')

In [31]:
df_new

          Age  Gender  Speed_of_Impact  Helmet_Used  Seatbelt_Used  Survived
0    0.843704       0        -1.456949            0              0         1
1    1.715924       0        -0.819848            0              1         1
2    0.172767       1        -0.819848            1              1         0
3   -0.766547       1         1.560897            0              1         0
4    1.112080       0        -1.021038            1              1         0
..        ...     ...              ...          ...            ...       ...
195  1.715924       0         1.359707            0              1         1
196 -0.900734       0        -0.652190            0              1         1
197  0.977892       1         1.326175            0              1         1
198 -1.571672       1         1.091454            0              1         1
199  0.843704       0        -0.920443            0              1         1

[200 rows x 6 columns]

In [33]:
def check_imbalance(df_new):
    for col in df_new.columns:
        print(f"\nColumn: {col}")
        value_counts= df_new[col].value_counts(normalize=True)*100
        print(value_counts)
check_imbalance(df_new)

Column: Age
Age
 0.843704    4.5
 1.179173    4.5
-0.766547    3.5
-0.162702    3.5
 0.105673    3.5
-0.833640    3.0
-1.236203    3.0
 0.575329    3.0
-1.169109    2.5
-1.638766    2.5
 1.648830    2.5
-0.095609    2.5
 1.380455    2.5
-1.303297    2.5
 1.246267    2.5
 1.044986    2.5
-0.028515    2.5
-1.705860    2.5
 1.715924    2.0
-0.363984    2.0
-1.034922    2.0
-0.229796    2.0
 0.172767    2.0
 0.910798    2.0
 0.642423    2.0
-1.571672    2.0
-0.296890    2.0
 0.441142    2.0
 0.709517    2.0
-1.504578    2.0
 0.038579    2.0
 0.977892    1.5
-0.900734    1.5
 0.374048    1.5
 0.239860    1.5
-0.565265    1.5
-0.431078    1.0
 1.112080    1.0
 0.508235    1.0
 1.514642    1.0
-0.967828    1.0
-0.699453    1.0
 1.581736    1.0
-1.437484    1.0
 1.447549    1.0
-1.370391    1.0
-0.632359    1.0
 0.776611    0.5
-0.498171    0.5
-1.102016    0.5
 0.306954    0.5
Name: proportion, dtype: float64

Column: Gender
Gender
0    55.5
1    44.5
Name: proportion, dtype: float64

Column: Speed_of_Impact
Speed_of_Impact
 0.219632    3.5
 0.018442    3.0
-1.188696    3.0
 0.588480    3.0
 1.359707    2.5
            ...
 1.259112    0.5
 0.890264    0.5
 0.957328    0.5
 1.326175    0.5
 1.091454    0.5
Name: proportion, Length: 80, dtype: float64

Column: Helmet_Used
Helmet_Used
1    55.5
0    44.5
Name: proportion, dtype: float64

Column: Seatbelt_Used
Seatbelt_Used
1    55.5
0    44.5
Name: proportion, dtype: float64

Column: Survived
Survived
1    50.5
0    49.5
Name: proportion, dtype: float64

In [34]:
df_new.head

<bound method NDFrame.head of           Age  Gender  Speed_of_Impact  Helmet_Used  Seatbelt_Used  Survived
0    0.843704       0        -1.456949            0              0         1
1    1.715924       0        -0.819848            0              1         1
2    0.172767       1        -0.819848            1              1         0
3   -0.766547       1         1.560897            0              1         0
4    1.112080       0        -1.021038            1              1         0
..        ...     ...              ...          ...            ...       ...
195  1.715924       0         1.359707            0              1         1
196 -0.900734       0        -0.652190            0              1         1
197  0.977892       1         1.326175            0              1         1
198 -1.571672       1         1.091454            0              1         1
199  0.843704       0        -0.920443            0              1         1

[200 rows x 6 columns]>

In [36]:
X=df_new[['Age','Gender','Speed_of_Impact','Helmet_Used','Seatbelt_Used']]
y=df_new[['Survived']]

In [38]:
print(df['Survived'].value_counts(normalize=True))

Survived
1    0.505
0    0.495
Name: proportion, dtype: float64

In [40]:
from sklearn.model_selection import train_test_split 
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score,precision_score,recall_score,auc,roc_curve,classification_report
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import RandomForestClassifier

In [41]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [49]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
#initialise models
models={
    'SVM': SVC(kernel='linear',probability=True,random_state=42,class_weight='balanced'),
    'Logistic Regression': LogisticRegression(random_state=42,class_weight='balanced'),
    'Random Forest': RandomForestClassifier(random_state=42,class_weight='balanced')
}
#train and evaluate models
for name, model in models.items():
    model.fit(X_train,y_train)
    y_pred= model.predict(X_test)
    print(f'\nModel Name: {name}')
    print(f'\nModel Accuracy: {accuracy_score(y_test,y_pred):.2f}')
    print(classification_report(y_test,y_pred))

Model Name: SVM

Model Accuracy: 0.47
              precision    recall  f1-score   support

           0       0.52      0.68      0.59        22
           1       0.36      0.22      0.28        18

    accuracy                           0.47        40
   macro avg       0.44      0.45      0.43        40
weighted avg       0.45      0.47      0.45        40


Model Name: Logistic Regression

Model Accuracy: 0.57
              precision    recall  f1-score   support

           0       0.59      0.73      0.65        22
           1       0.54      0.39      0.45        18

    accuracy                           0.57        40
   macro avg       0.57      0.56      0.55        40
weighted avg       0.57      0.57      0.56        40


Model Name: Random Forest

Model Accuracy: 0.55
              precision    recall  f1-score   support

           0       0.58      0.64      0.61        22
           1       0.50      0.44      0.47        18

    accuracy                           0.55        40
   macro avg       0.54      0.54      0.54        40
weighted avg       0.55      0.55      0.55        40